pub mod model;
pub mod state_machine;
pub mod steps;

pub use model::{
    AccessMode, Operation, OperationEffect, OperationKind, OperationResource, OperationState,
    OperationStep, OperationStepState, ResourceKind, OPERATION_PLAN_SCHEMA_V1,
    OPERATION_PLAN_SCHEMA_V2,
};
pub use state_machine::is_valid_transition;
pub use steps::{
    OperationStepKind, INSTALL_STEP_CLEANUP_STAGING, INSTALL_STEP_COMMIT_DATABASE,
    INSTALL_STEP_INSPECT_AND_STAGE, INSTALL_STEP_PUBLISH_DEPLOYMENT,
    INSTALL_STEP_QUARANTINE_PUBLISHED, INSTALL_STEP_RETAIN_ARTIFACT, INSTALL_STEP_VERIFY_STAGED,
    REMOVAL_STEP_COMMIT_DATABASE, REMOVAL_STEP_QUARANTINE_DEPLOYMENT,
    REMOVAL_STEP_RESTORE_QUARANTINED, SMAPI_STEP_DOWNLOAD_INSTALLER, SMAPI_STEP_INSTALL_FILES,
    SMAPI_STEP_PERSIST_STATE,
};
