// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdoptionFailureDto } from "./AdoptionFailureDto";

/**
 * What adopting did. The original folder is never changed.
 */
export type AdoptionResultDto = { profile_id: string, profile_name: string, adopted: Array<string>, failed: Array<AdoptionFailureDto>, 
/**
 * Everything in the Mods folder that was not adopted, left as it is.
 */
left_in_place: Array<string>, };
