// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdoptComponentDto = { unique_id: string, name: string, version: string, author: string, update_keys: Array<string>, 
/**
 * UniqueIDs it requires, so a partial choice can show what it leaves out.
 */
requires: Array<string>, };
