// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdoptableModDto } from "./AdoptableModDto";
import type { UnknownEntryDto } from "./UnknownEntryDto";

/**
 * What an unmanaged Mods folder holds, read without changing it.
 */
export type AdoptionScanDto = { mods_dir: string, mods: Array<AdoptableModDto>, unknown: Array<UnknownEntryDto>, 
/**
 * Folders SMAPI itself ships; never adopted.
 */
runtime: Array<string>, 
/**
 * Signs another mod manager deployed these files.
 */
manager_markers: Array<string>, 
/**
 * Identifies exactly what was scanned; adopting checks it again.
 */
fingerprint: string, total_bytes: number, };
