// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppErrorCategory } from "./AppErrorCategory";
import type { Recoverability } from "./Recoverability";

/**
 * The error contract that crosses the Tauri IPC boundary.
 *
 * Every field is carried over from AppError unchanged, including the operation
 * ID that recovery-specific UX needs. Category and recoverability reuse the
 * application enums so the generated TypeScript contract stays a closed union
 * instead of an unconstrained string.
 */
export type ApiErrorDto = { code: string, category: AppErrorCategory, summary: string, technical_details: string | null, context: string | null, recoverability: Recoverability, operation_id: string | null, };
