// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiErrorDto = { code: string, category: string, summary: string, technical_details: string | null, context: string | null, recoverability: string, operation_id: string | null, };
