// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One health finding as it was when a profile last worked.
 */
export type BaselineFindingDto = { fingerprint: string, code: string, severity: string, title: string, };
