// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulkToggleFailureDto } from "./BulkToggleFailureDto";

/**
 * What happened to each mod in a bulk enable or disable.
 */
export type BulkToggleResultDto = { 
/**
 * Names of the mods now in the requested state.
 */
changed: Array<string>, failed: Array<BulkToggleFailureDto>, };
