// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleComponentDto } from "./BundleComponentDto";

/**
 * What a bundle contains, read without installing anything.
 */
export type BundlePreviewDto = { profile_name: string, generated_at: string, components: Array<BundleComponentDto>, 
/**
 * Names of mods the bundle lists but does not carry.
 */
missing_packages: Array<string>, warnings: Array<string>, 
/**
 * UniqueIDs of mods whose settings the bundle carries.
 */
settings_for: Array<string>, 
/**
 * Requirements no mod in the bundle provides, as "Mod needs Id".
 */
unresolved_requirements: Array<string>, 
/**
 * Mods whose files were changed outside the manager when exported.
 */
locally_modified: Array<string>, 
/**
 * When and why the exported profile was frozen, if it was.
 */
frozen_at: string | null, frozen_reason: string | null, };
