// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleComponentDto = { unique_id: string, name: string, version: string, enabled: boolean, 
/**
 * Whether the bundle contains the package needed to install it.
 */
package_included: boolean, 
/**
 * The author marked it optional: it is installed only if chosen.
 */
optional: boolean, };
