// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleFailureDto } from "./BundleFailureDto";

export type BundleImportDto = { profile_id: string, profile_name: string, installed: Array<string>, 
/**
 * Installed but left disabled, as in the original profile.
 */
disabled: Array<string>, failures: Array<BundleFailureDto>, 
/**
 * Mods whose settings from the bundle were written.
 */
settings_applied: Array<string>, 
/**
 * Optional mods the bundle offered that were not chosen.
 */
declined_optional: Array<string>, };
