// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleComponentDto } from "./BundleComponentDto";

/**
 * What a bundle contains, read without installing anything.
 */
export type BundlePreviewDto = { profile_name: string, generated_at: string, components: Array<BundleComponentDto>, 
/**
 * Names of mods the bundle lists but does not carry.
 */
missing_packages: Array<string>, warnings: Array<string>, };
