// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleExportDto = { 
/**
 * Where the bundle was written.
 */
path: string, component_count: number, package_count: number, 
/**
 * Mods whose package is no longer stored, so the bundle cannot carry them.
 */
missing_packages: Array<string>, 
/**
 * Mods whose settings were included.
 */
settings_included: Array<string>, };
