// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleanupItemDto } from "./CleanupItemDto";

export type CleanupPreviewDto = { items: Array<CleanupItemDto>, reclaimable_bytes: number, protected_bytes: number, 
/**
 * Set when something running right now protects items that would
 * otherwise be removable.
 */
blocked_reason: string | null, };
