// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CleanupOutcomeDto = { id: string, label: string, 
/**
 * "removed", "failed" or "skipped".
 */
outcome: string, 
/**
 * Why an item failed or was skipped.
 */
message: string | null, size_bytes: number, };
