// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One item the storage cleanup found, and whether it may be removed.
 */
export type CleanupItemDto = { 
/**
 * Stable identifier to pass back when running the cleanup.
 */
id: string, 
/**
 * "cache", "unused_package", "operation_leftover" or "protected".
 */
category: string, label: string, 
/**
 * Why the item is in this category, in plain words.
 */
detail: string, size_bytes: number, removable: boolean, };
