// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A deleted profile whose folder is still in the trash, with its record.
 */
export type DeletedProfileDto = { 
/**
 * The trash entry, used to bring it back.
 */
entry: string, name: string, deleted_at: string, mod_count: number, };
