// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingDto } from "./FindingDto";
import type { LogSummaryDto } from "./LogSummaryDto";
import type { PlatformPathDto } from "./PlatformPathDto";

export type DiagnosticsDto = { 
/**
 * Structured reading of `raw_log`; empty when the log could not be read.
 */
log_summary: LogSummaryDto, session_id: string | null, session_state: string | null, findings: Array<FindingDto>, raw_log: string, log_file_path: string, 
/**
 * The platform this build runs on, so a report always describes the code
 * that produced it rather than what the UI assumes.
 */
host_operating_system: string, 
/**
 * Where the manager keeps its database and profile storage.
 */
app_data_dir: string, 
/**
 * Where the manager keeps downloaded artifacts and the SMAPI installer.
 */
cache_dir: string, 
/**
 * The locations the Steam discovery searched on this host.
 */
steam_installations_checked: Array<string>, 
/**
 * Where the SMAPI log would live for each platform the manager supports,
 * so a user can find it even when the manager is not the one that wrote it.
 */
smapi_log_locations: Array<PlatformPathDto>, 
/**
 * How the log on disk relates to the session: "current_session" (it
 * started after that session was launched), "stale" (it is older),
 * "unmatched" (there is no session), "unknown" (the log's start time
 * could not be read) or "none" (no log).
 */
log_match: string, 
/**
 * When the log says it started, if it could be read.
 */
log_started_at: string | null, 
/**
 * Why the log could not be read, when it exists but reading failed.
 */
log_read_error: string | null, };
