// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingDto } from "./FindingDto";
import type { PlatformPathDto } from "./PlatformPathDto";

export type DiagnosticsDto = { session_id: string | null, session_state: string | null, findings: Array<FindingDto>, raw_log: string, log_file_path: string, 
/**
 * The platform this build runs on, so a report always describes the code
 * that produced it rather than what the UI assumes.
 */
host_operating_system: string, 
/**
 * Where the manager keeps its database and profile storage.
 */
app_data_dir: string, 
/**
 * Where the manager keeps downloaded artifacts and the SMAPI installer.
 */
cache_dir: string, 
/**
 * The locations the Steam discovery searched on this host.
 */
steam_installations_checked: Array<string>, 
/**
 * Where the SMAPI log would live for each platform the manager supports,
 * so a user can find it even when the manager is not the one that wrote it.
 */
smapi_log_locations: Array<PlatformPathDto>, };
