// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The parts of a dismissed finding that are compared when it comes back.
 */
export type DismissedSnapshotDto = { severity: string, summary: string, evidence: Array<string>, };
