// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A finding the user chose to stop seeing, and what it said when they did.
 */
export type DismissedFindingDto = { fingerprint: string, 
/**
 * Digest of the finding's content. A finding whose content differs from
 * this is shown again.
 */
signature: string, };
