// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaselineFindingDto } from "./BaselineFindingDto";
import type { FrozenModDto } from "./FrozenModDto";

/**
 * The mods and runtime a profile last ran successfully with.
 */
export type KnownGoodDto = { profile_id: string, recorded_at: string, game_version: string | null, smapi_version: string | null, mods: Array<FrozenModDto>, 
/**
 * The health findings at that moment. `None` for records made before
 * findings were kept, so there is nothing to compare with.
 */
findings: Array<BaselineFindingDto> | null, };
