// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LaunchSessionDto = { id: string, profile_id: string, state: string, launched_at: string, ended_at: string | null, pid: number | null, verified_mods: Array<string>, verification_details: string | null, };
