// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a download link answered when checked. One check is a moment,
 * not a verdict: a site that is down now may be up later.
 */
export type LinkCheckDto = { url: string, 
/**
 * "reachable", "not_found" (404 or 410), "error" (another HTTP status),
 * "unreachable" (no answer) or "not_checked" (not a web address).
 */
state: string, status: number | null, checked_at: string, };
