// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One place on disk the user may want to find, with what it is for.
 */
export type LocationDto = { 
/**
 * Stable id, used to open it (the path itself is never sent back).
 */
id: string, label: string, 
/**
 * `None` when it is not known, for example no game is selected.
 */
path: string | null, exists: boolean, 
/**
 * What it holds, and whether it is safe to clear.
 */
note: string, };
