// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One SMAPI log error line.
 */
export type LogErrorDto = { line: number, source: string, 
/**
 * "missing_dependency", "content_pack", "patch", "exception", "file" or
 * "other": a guess from the wording.
 */
kind: string, message: string, };
