// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogSourceCountDto = { source: string, errors: number, warnings: number, first_error_line: number | null, };
