// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's own notes about a mod. Keyed by UniqueID, so they follow the mod
 * into every profile, and never change what is installed or loaded.
 */
export type ModAnnotationDto = { unique_id: string, favourite: boolean, tags: Array<string>, note: string, };
