// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModListItemDto = { profile_component_id: string, unique_id: string, name: string, author: string, version: string, description: string | null, enabled: boolean, installed_reason: string, deployment_id: string, artifact_hash: string, installed_at: string, };
