// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModListItemDto = { profile_component_id: string, unique_id: string, name: string, author: string, version: string, description: string | null, enabled: boolean, installed_reason: string, deployment_id: string, artifact_hash: string, installed_at: string, 
/**
 * The mod's folder is not where the manager put it (moved or deleted
 * outside the manager).
 */
folder_missing: boolean, 
/**
 * Built-in grouping from the manifest, separate from user tags:
 * "content_pack" (has ContentPackFor), "smapi_mod" (has an EntryDll)
 * or "other".
 */
kind: string, 
/**
 * The manifest's UpdateKeys (such as "Nexus:1915"): where the author
 * says the mod is published. As declared, not verified.
 */
update_keys: Array<string>, 
/**
 * UniqueIDs the manifest says it requires, its content-pack host first.
 */
requires: Array<string>, };
