// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanFileDto } from "./PlanFileDto";

/**
 * The files an install put in a mod's folder, and the package behind them.
 */
export type ModPackageFilesDto = { 
/**
 * False for installs made before file records were kept.
 */
recorded: boolean, files: Array<PlanFileDto>, 
/**
 * Every mod that came from the same package, in any profile folder of
 * this one.
 */
package_mods: Array<string>, artifact_hash: string, package_stored: boolean, 
/**
 * Whether the stored package still matches its checksum; null when it
 * is not stored.
 */
package_intact: boolean | null, };
