// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mod whose required dependencies are not all met.
 */
export type ModProblemDto = { profile_component_id: string, 
/**
 * UniqueIDs of required mods or hosts that are missing, disabled or too old.
 */
unmet_requirements: Array<string>, };
