// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModDependentDto } from "./ModDependentDto";
import type { ModRequirementDto } from "./ModRequirementDto";

/**
 * Why a mod is in the profile and how it relates to the others.
 */
export type ModRelationsDto = { 
/**
 * "direct", "dependency" or "bundle_companion".
 */
installed_reason: string, 
/**
 * The reason in plain words, including what the manager does not know.
 */
reason_detail: string, requires: Array<ModRequirementDto>, required_by: Array<ModDependentDto>, 
/**
 * Chains such as ["Top", "Middle", "Missing.UniqueID"], each ending at a
 * requirement that is not satisfied. Names are used where known.
 */
broken_chains: Array<Array<string>>, };
