// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperationEffectDto = { id: string, operation_id: string, entity_type: string, entity_id: string, change_kind: string, occurred_at: string, };
