// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperationChangeDto = { 
/**
 * "added", "removed", "profile_created", "copied_from" or the recorded kind.
 */
change: string, name: string | null, unique_id: string | null, version: string | null, };
