// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file of an archive under review.
 */
export type PlanFileDto = { path: string, size_bytes: number, installed: boolean, };
