// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a launch would be blocked or cautioned by, before the user clicks.
 */
export type PreflightDto = { can_launch: boolean, blockers: Array<string>, warnings: Array<string>, };
