// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What deleting an archived profile will remove, shown before it happens.
 */
export type ProfileDeletePreviewDto = { profile_id: string, name: string, mod_count: number, 
/**
 * Size of the profile's own folder (its installed mods and settings).
 */
folder_bytes: number, 
/**
 * Packages the profile used. They are kept; other profiles may use them
 * and storage cleanup can remove the unused ones later.
 */
packages_kept: number, 
/**
 * Why it cannot be deleted right now, if it cannot.
 */
blocked_reason: string | null, };
