// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a clean reinstall did.
 */
export type ReinstallResultDto = { 
/**
 * The mods reinstalled from the package, with versions.
 */
mods: Array<string>, 
/**
 * Settings files carried over from the old copy.
 */
kept_settings: Array<string>, 
/**
 * True when the mod was disabled before and was left disabled.
 */
left_disabled: boolean, };
