// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplacementDto } from "./ReplacementDto";

/**
 * What replacing installed mods with another version did.
 */
export type ReplaceResultDto = { replaced: Array<ReplacementDto>, kept_settings: Array<string>, left_disabled: boolean, };
