// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One installed mod a package would replace.
 */
export type ReplacementDto = { profile_component_id: string, unique_id: string, name: string, installed_version: string, incoming_version: string, 
/**
 * "upgrade", "downgrade", "same", or "different" when a version cannot
 * be ordered.
 */
direction: string, };
