// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplacementDto } from "./ReplacementDto";

/**
 * What replacing installed mods with another version did.
 */
export type ReplaceResultDto = { replaced: Array<ReplacementDto>, kept_settings: Array<string>, left_disabled: boolean, 
/**
 * Where the settings were saved before the change, when there were any.
 */
settings_backup: string | null, 
/**
 * The restore point saved automatically before the change.
 */
restore_point: string | null, };
