// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What restoring a point would do, worked out before anything changes.
 */
export type RestorePlanDto = { point_id: string, 
/**
 * False when a package the point needs is no longer kept or is damaged;
 * the point is then not restored at all.
 */
available: boolean, unavailable: Array<string>, remove: Array<string>, install: Array<string>, change_version: Array<string>, enable: Array<string>, disable: Array<string>, };
