// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrozenModDto } from "./FrozenModDto";

/**
 * A saved state of a profile's mods that it can be restored to.
 */
export type RestorePointDto = { id: string, label: string, created_at: string, mods: Array<FrozenModDto>, };
