// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much recovery data storage cleanup keeps. Older items become
 * removable; nothing is removed until a cleanup is run.
 */
export type RetentionPolicyDto = { 
/**
 * Newest backups kept for each save.
 */
keep_save_backups: number, 
/**
 * Newest backups kept for each mod's settings.
 */
keep_settings_backups: number, 
/**
 * Days a deleted profile's folder stays in the trash.
 */
keep_trash_days: number, };
