// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveBackupDto = { id: string, save_id: string, created_at: string, size_bytes: number, 
/**
 * What the backup was made for, such as an experiment, when known.
 */
note: string | null, };
