// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveDto } from "./SaveDto";

export type SavesDto = { 
/**
 * Where the game keeps saves on this computer, if it could be found.
 */
saves_dir: string | null, saves: Array<SaveDto>, };
