// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The checksum of one settings file in a profile; never its contents.
 */
export type SettingFileHashDto = { 
/**
 * Lower-case UniqueID of the mod.
 */
unique_id: string, path: string, sha256: string, };
