// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupAccessCheckDto } from "./SetupAccessCheckDto";

/**
 * What SMAPI setup will do, worked out from the same release policy and
 * locations the installation uses, before anything is changed.
 */
export type SetupPreviewDto = { game_path: string, smapi_version: string, smapi_source: string, smapi_sha256: string, supported_game_version: string, 
/**
 * SMAPI already in the game folder, if any.
 */
installed_smapi: string | null, 
/**
 * Changes to the game folder.
 */
modifies: Array<string>, 
/**
 * Folders the manager creates and owns.
 */
creates: Array<string>, 
/**
 * What is only looked at.
 */
reads: Array<string>, 
/**
 * Things already present that matter to setup.
 */
notices: Array<string>, checks: Array<SetupAccessCheckDto>, 
/**
 * False when a required check failed; setup then does not start.
 */
can_proceed: boolean, };
