// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One location setup needs, and whether it can be used.
 */
export type SetupAccessCheckDto = { label: string, path: string, 
/**
 * "read and write" etc., in words.
 */
needs: string, ok: boolean, problem: string | null, 
/**
 * What to do about a failure, without asking for administrator rights.
 */
remedy: string | null, };
