// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedSettingFileDto } from "./SharedSettingFileDto";

/**
 * One mod's settings files as text, read for sharing in a recipe.
 */
export type SharedSettingsDto = { unique_id: string, files: Array<SharedSettingFileDto>, 
/**
 * Files left out, with why (not text, or too large).
 */
skipped: Array<string>, };
