// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkippedModDto = { name: string, version: string | null, reason: string, missing_dependencies: Array<string>, 
/**
 * 1-based line in the SMAPI log.
 */
line: number, };
