// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmapiReleaseDto = { version: string, published_at: string | null, prerelease: boolean, 
/**
 * "published" (SMAPI published a checksum), "recorded" (no published
 * checksum, but this manager recorded one when it installed it) or
 * "none".
 */
checksum: string, min_game: string | null, max_game: string | null, 
/**
 * "compatible", "game_too_old", "game_too_new" or "unknown".
 */
compatibility: string, notes_url: string, 
/**
 * Its installer is kept here, so it installs without the network.
 */
installer_kept: boolean, is_installed: boolean, is_recommended: boolean, };
