// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmapiReleaseDto } from "./SmapiReleaseDto";

/**
 * The SMAPI releases the manager can install, with how each fits the game.
 */
export type SmapiCatalogDto = { 
/**
 * Newest first.
 */
releases: Array<SmapiReleaseDto>, 
/**
 * "online" (just read), "cached" (read earlier) or "builtin" (only the
 * release this manager ships with).
 */
source: string, checked_at: string | null, 
/**
 * Why reading the list online failed, when it did.
 */
error: string | null, game_version: string | null, recommended: string | null, installed: string | null, };
