// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmapiStatusDto = { is_installed: boolean, observed_version: string | null, tested_version: string, is_compatible: boolean, 
/**
 * "absent", "installed" or "partial" (some SMAPI files are missing).
 */
state: string, 
/**
 * How the installed version relates to the tested one: "same",
 * "newer", "older", "unknown" (installed but unreadable) or "absent".
 */
comparison: string, 
/**
 * What the state is based on.
 */
evidence: Array<string>, };
