// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmapiStatusDto = { is_installed: boolean, observed_version: string | null, tested_version: string, is_compatible: boolean, };
