// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A package the manager already stores that provides a mod.
 */
export type StoredCandidateDto = { artifact_hash: string, name: string, version: string, original_filename: string, 
/**
 * Whether this version meets the requirement; null when the versions
 * could not be compared.
 */
meets_minimum: boolean | null, };
