// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What enabling or disabling a mod would touch, shown before it happens.
 */
export type ToggleImpactDto = { 
/**
 * Every mod that moves with it because they share one package folder.
 */
affected_mods: Array<string>, 
/**
 * Enabled mods that require it and would stop loading when it is disabled.
 */
dependents: Array<string>, 
/**
 * Requirements of what is being enabled that are not enabled.
 */
unmet_requirements: Array<string>, };
