// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A duplicate that was started but not finished.
 */
export type UnfinishedCopyDto = { profile_id: string, profile_name: string, 
/**
 * The profile it is a copy of, by its name at the time.
 */
source_name: string, 
/**
 * How many mods the finished copy should have.
 */
expected_mods: number, };
