// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UnknownEntryDto = { name: string, size_bytes: number, is_folder: boolean, reason: string, };
