[package]
name = "manager-infra"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
manager-core.workspace = true
manager-app.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rusqlite.workspace = true
zip.workspace = true
sha2.workspace = true
fs2.workspace = true
tracing.workspace = true
tempfile.workspace = true
chrono.workspace = true
libc.workspace = true
uuid.workspace = true
directories.workspace = true
async-trait.workspace = true
reqwest = { workspace = true, features = ["stream", "blocking"] }
tokio.workspace = true
futures-util = "0.3"

[dev-dependencies]
tempfile.workspace = true

